<a href="https://colab.research.google.com/github/porterac/ME_275/blob/main/Linear_Algebra_in_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Linear Algebra

The purpose of this page is to give an overview of how to solve A*x = b using python. A simple understanding of matrices is assumed (for example what a NxM matrix means). However, an understanding of system conditioning is not assumed.

In [6]:
import numpy as np

A = np.array([[1,2],[4,5]])
print(A)
A_t = A.T
print(A_t)
A_inv = np.linalg.inv(A)
print(A_inv)

[[1 2]
 [4 5]]
[[1 4]
 [2 5]]
[[-1.66666667  0.66666667]
 [ 1.33333333 -0.33333333]]
